// Loads the static synthetic datasets from /data at startup.
//
// This demo intentionally has no database: the JSON files generated by
// `npm run generate-data` (see /data/generate.mjs) are the single source of
// truth, read once into memory. This keeps the workshop easy to run and
// modify - swapping this module for a real database client is one of the
// natural "next steps" exercises for participants.
import { readFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import type { Account, Customer, Instrument, Investment, MarketDataPoint, Transaction } from './types.js'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
// Both `src` (via tsx) and `dist` (built) sit directly under /api, so the
// data folder is always two levels up from here.
const DATA_DIR = path.join(__dirname, '..', '..', 'data')

function loadJson<T>(fileName: string): T {
  const filePath = path.join(DATA_DIR, fileName)
  const raw = readFileSync(filePath, 'utf8')
  return JSON.parse(raw) as T
}

export const customers: Customer[] = loadJson<Customer[]>('customers.json')
export const accounts: Account[] = loadJson<Account[]>('accounts.json')
export const transactions: Transaction[] = loadJson<Transaction[]>('transactions.json')
export const investments: Investment[] = loadJson<Investment[]>('investments.json')
export const marketData: MarketDataPoint[] = loadJson<MarketDataPoint[]>('market_data.json')

const customerById = new Map(customers.map((c) => [c.customer_id, c]))
const accountsByCustomer = new Map<string, Account[]>()
for (const account of accounts) {
  const list = accountsByCustomer.get(account.customer_id) ?? []
  list.push(account)
  accountsByCustomer.set(account.customer_id, list)
}
const transactionsByCustomer = new Map<string, Transaction[]>()
for (const tx of transactions) {
  const list = transactionsByCustomer.get(tx.customer_id) ?? []
  list.push(tx)
  transactionsByCustomer.set(tx.customer_id, list)
}
const investmentsByCustomer = new Map<string, Investment[]>()
for (const inv of investments) {
  const list = investmentsByCustomer.get(inv.customer_id) ?? []
  list.push(inv)
  investmentsByCustomer.set(inv.customer_id, list)
}
const marketDataByTicker = new Map<string, MarketDataPoint[]>()
for (const point of marketData) {
  const list = marketDataByTicker.get(point.ticker) ?? []
  list.push(point)
  marketDataByTicker.set(point.ticker, list)
}
for (const list of marketDataByTicker.values()) {
  list.sort((a, b) => (a.date < b.date ? -1 : a.date > b.date ? 1 : 0))
}

export function getCustomer(customerId: string): Customer | undefined {
  return customerById.get(customerId)
}
export function getAccountsFor(customerId: string): Account[] {
  return accountsByCustomer.get(customerId) ?? []
}
export function getTransactionsFor(customerId: string): Transaction[] {
  return transactionsByCustomer.get(customerId) ?? []
}
export function getInvestmentsFor(customerId: string): Investment[] {
  return investmentsByCustomer.get(customerId) ?? []
}
export function getMarketDataFor(ticker: string): MarketDataPoint[] {
  return marketDataByTicker.get(ticker) ?? []
}

// All unique instruments across the entire synthetic universe, with latest price.
export function getAllInstruments(): Instrument[] {
  const seen = new Map<string, Investment>()
  for (const inv of investments) {
    if (!seen.has(inv.ticker)) {
      seen.set(inv.ticker, inv)
    }
  }
  return [...seen.values()].map((inv) => ({
    ticker: inv.ticker,
    name: inv.name,
    asset_type: inv.asset_type,
    sector: inv.sector,
    geography: inv.geography,
    current_price: inv.current_price,
    currency: inv.currency,
  }))
}

// All holdings across all customers (flattened).
export function getAllHoldings(): Investment[] {
  return investments
}
